/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppbarRouteImport } from './routes/_appbar'
import { Route as AppbarIndexRouteImport } from './routes/_appbar/index'
import { Route as AppbarIssuesRouteImport } from './routes/_appbar/issues'
import { Route as AppbarHubRouteImport } from './routes/_appbar/hub'
import { Route as AppbarSidebarRouteImport } from './routes/_appbar/_sidebar'
import { Route as AppbarFuelRouteImport } from './routes/_appbar/_fuel'
import { Route as AppbarAdminRouteImport } from './routes/_appbar/_admin'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AppbarSidebarSettingsRouteImport } from './routes/_appbar/_sidebar/settings'
import { Route as AppbarSidebarInventoryRouteImport } from './routes/_appbar/_sidebar/inventory'
import { Route as AppbarSidebarHubRouteImport } from './routes/_appbar/_sidebar/hub'
import { Route as AppbarSidebarCipherRouteImport } from './routes/_appbar/_sidebar/cipher'
import { Route as AppbarFuelKardpollRouteImport } from './routes/_appbar/_fuel/kardpoll'
import { Route as AppbarFuelFuelRecRouteImport } from './routes/_appbar/_fuel/fuel-rec'
import { Route as AppbarFuelFuelInvoicingRouteImport } from './routes/_appbar/_fuel/fuel-invoicing'
import { Route as AppbarAdminSidebarRouteImport } from './routes/_appbar/_admin/_sidebar'
import { Route as AppbarSidebarSettingsUsersRouteImport } from './routes/_appbar/_sidebar/settings/users'
import { Route as AppbarSidebarSettingsRolesRouteImport } from './routes/_appbar/_sidebar/settings/roles'
import { Route as AppbarSidebarSettingsLogsRouteImport } from './routes/_appbar/_sidebar/settings/logs'
import { Route as AppbarSidebarInventoryCoremarkInitialOrderRouteImport } from './routes/_appbar/_sidebar/inventory/coremark-initial-order'
import { Route as AppbarSidebarHubReceivablesRouteImport } from './routes/_appbar/_sidebar/hub/receivables'
import { Route as AppbarSidebarHubPayablesRouteImport } from './routes/_appbar/_sidebar/hub/payables'
import { Route as AppbarSidebarHubCdnRouteImport } from './routes/_appbar/_sidebar/hub/cdn'
import { Route as AppbarSidebarCipherUnlockRouteImport } from './routes/_appbar/_sidebar/cipher/unlock'
import { Route as AppbarSidebarCipherLockRouteImport } from './routes/_appbar/_sidebar/cipher/lock'
import { Route as AppbarSidebarAcademyCoursesRouteImport } from './routes/_appbar/_sidebar/academy/courses'
import { Route as AppbarAdminSidebarSubscriptionsRouteImport } from './routes/_appbar/_admin/_sidebar/subscriptions'
import { Route as AppbarAdminSidebarSiteAssetsRouteImport } from './routes/_appbar/_admin/_sidebar/site-assets'
import { Route as AppbarAdminSidebarPersonnelRouteImport } from './routes/_appbar/_admin/_sidebar/personnel'
import { Route as AppbarAdminSidebarCredentialsRouteImport } from './routes/_appbar/_admin/_sidebar/credentials'
import { Route as AppbarAdminSidebarAssetsRouteImport } from './routes/_appbar/_admin/_sidebar/assets'
import { Route as AppbarAdminSidebarAccessRouteImport } from './routes/_appbar/_admin/_sidebar/access'
import { Route as AppbarSidebarAcademyCoursesIndexRouteImport } from './routes/_appbar/_sidebar/academy/courses/index'
import { Route as AppbarAdminSidebarSiteAssetsIndexRouteImport } from './routes/_appbar/_admin/_sidebar/site-assets/index'
import { Route as AppbarAdminSidebarPersonnelIndexRouteImport } from './routes/_appbar/_admin/_sidebar/personnel/index'
import { Route as AppbarSidebarAcademyCoursesCourseIdRouteImport } from './routes/_appbar/_sidebar/academy/courses/$courseId'
import { Route as AppbarAdminSidebarSubscriptionsListRouteImport } from './routes/_appbar/_admin/_sidebar/subscriptions/list'
import { Route as AppbarAdminSidebarSubscriptionsCategoriesRouteImport } from './routes/_appbar/_admin/_sidebar/subscriptions/categories'
import { Route as AppbarAdminSidebarSiteAssetsListRouteImport } from './routes/_appbar/_admin/_sidebar/site-assets/list'
import { Route as AppbarAdminSidebarSiteAssetsAddRouteImport } from './routes/_appbar/_admin/_sidebar/site-assets/add'
import { Route as AppbarAdminSidebarCredentialsListRouteImport } from './routes/_appbar/_admin/_sidebar/credentials/list'
import { Route as AppbarAdminSidebarCredentialsCategoriesRouteImport } from './routes/_appbar/_admin/_sidebar/credentials/categories'
import { Route as AppbarAdminSidebarAssetsPersonnelRouteImport } from './routes/_appbar/_admin/_sidebar/assets/personnel'
import { Route as AppbarAdminSidebarAssetsLocationRouteImport } from './routes/_appbar/_admin/_sidebar/assets/location'
import { Route as AppbarAdminSidebarAssetsDevicesRouteImport } from './routes/_appbar/_admin/_sidebar/assets/devices'
import { Route as AppbarAdminSidebarAccessResourcesRouteImport } from './routes/_appbar/_admin/_sidebar/access/resources'
import { Route as AppbarAdminSidebarAccessPersonnelRouteImport } from './routes/_appbar/_admin/_sidebar/access/personnel'

const AppbarRoute = AppbarRouteImport.update({
  id: '/_appbar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppbarIndexRoute = AppbarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppbarRoute,
} as any)
const AppbarIssuesRoute = AppbarIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AppbarRoute,
} as any)
const AppbarHubRoute = AppbarHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AppbarRoute,
} as any)
const AppbarSidebarRoute = AppbarSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => AppbarRoute,
} as any)
const AppbarFuelRoute = AppbarFuelRouteImport.update({
  id: '/_fuel',
  getParentRoute: () => AppbarRoute,
} as any)
const AppbarAdminRoute = AppbarAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppbarRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppbarSidebarSettingsRoute = AppbarSidebarSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppbarSidebarRoute,
} as any)
const AppbarSidebarInventoryRoute = AppbarSidebarInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppbarSidebarRoute,
} as any)
const AppbarSidebarHubRoute = AppbarSidebarHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AppbarSidebarRoute,
} as any)
const AppbarSidebarCipherRoute = AppbarSidebarCipherRouteImport.update({
  id: '/cipher',
  path: '/cipher',
  getParentRoute: () => AppbarSidebarRoute,
} as any)
const AppbarFuelKardpollRoute = AppbarFuelKardpollRouteImport.update({
  id: '/kardpoll',
  path: '/kardpoll',
  getParentRoute: () => AppbarFuelRoute,
} as any)
const AppbarFuelFuelRecRoute = AppbarFuelFuelRecRouteImport.update({
  id: '/fuel-rec',
  path: '/fuel-rec',
  getParentRoute: () => AppbarFuelRoute,
} as any)
const AppbarFuelFuelInvoicingRoute = AppbarFuelFuelInvoicingRouteImport.update({
  id: '/fuel-invoicing',
  path: '/fuel-invoicing',
  getParentRoute: () => AppbarFuelRoute,
} as any)
const AppbarAdminSidebarRoute = AppbarAdminSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => AppbarAdminRoute,
} as any)
const AppbarSidebarSettingsUsersRoute =
  AppbarSidebarSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AppbarSidebarSettingsRoute,
  } as any)
const AppbarSidebarSettingsRolesRoute =
  AppbarSidebarSettingsRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AppbarSidebarSettingsRoute,
  } as any)
const AppbarSidebarSettingsLogsRoute =
  AppbarSidebarSettingsLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AppbarSidebarSettingsRoute,
  } as any)
const AppbarSidebarInventoryCoremarkInitialOrderRoute =
  AppbarSidebarInventoryCoremarkInitialOrderRouteImport.update({
    id: '/coremark-initial-order',
    path: '/coremark-initial-order',
    getParentRoute: () => AppbarSidebarInventoryRoute,
  } as any)
const AppbarSidebarHubReceivablesRoute =
  AppbarSidebarHubReceivablesRouteImport.update({
    id: '/receivables',
    path: '/receivables',
    getParentRoute: () => AppbarSidebarHubRoute,
  } as any)
const AppbarSidebarHubPayablesRoute =
  AppbarSidebarHubPayablesRouteImport.update({
    id: '/payables',
    path: '/payables',
    getParentRoute: () => AppbarSidebarHubRoute,
  } as any)
const AppbarSidebarHubCdnRoute = AppbarSidebarHubCdnRouteImport.update({
  id: '/cdn',
  path: '/cdn',
  getParentRoute: () => AppbarSidebarHubRoute,
} as any)
const AppbarSidebarCipherUnlockRoute =
  AppbarSidebarCipherUnlockRouteImport.update({
    id: '/unlock',
    path: '/unlock',
    getParentRoute: () => AppbarSidebarCipherRoute,
  } as any)
const AppbarSidebarCipherLockRoute = AppbarSidebarCipherLockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => AppbarSidebarCipherRoute,
} as any)
const AppbarSidebarAcademyCoursesRoute =
  AppbarSidebarAcademyCoursesRouteImport.update({
    id: '/academy/courses',
    path: '/academy/courses',
    getParentRoute: () => AppbarSidebarRoute,
  } as any)
const AppbarAdminSidebarSubscriptionsRoute =
  AppbarAdminSidebarSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AppbarAdminSidebarRoute,
  } as any)
const AppbarAdminSidebarSiteAssetsRoute =
  AppbarAdminSidebarSiteAssetsRouteImport.update({
    id: '/site-assets',
    path: '/site-assets',
    getParentRoute: () => AppbarAdminSidebarRoute,
  } as any)
const AppbarAdminSidebarPersonnelRoute =
  AppbarAdminSidebarPersonnelRouteImport.update({
    id: '/personnel',
    path: '/personnel',
    getParentRoute: () => AppbarAdminSidebarRoute,
  } as any)
const AppbarAdminSidebarCredentialsRoute =
  AppbarAdminSidebarCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AppbarAdminSidebarRoute,
  } as any)
const AppbarAdminSidebarAssetsRoute =
  AppbarAdminSidebarAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AppbarAdminSidebarRoute,
  } as any)
const AppbarAdminSidebarAccessRoute =
  AppbarAdminSidebarAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AppbarAdminSidebarRoute,
  } as any)
const AppbarSidebarAcademyCoursesIndexRoute =
  AppbarSidebarAcademyCoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppbarSidebarAcademyCoursesRoute,
  } as any)
const AppbarAdminSidebarSiteAssetsIndexRoute =
  AppbarAdminSidebarSiteAssetsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppbarAdminSidebarSiteAssetsRoute,
  } as any)
const AppbarAdminSidebarPersonnelIndexRoute =
  AppbarAdminSidebarPersonnelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppbarAdminSidebarPersonnelRoute,
  } as any)
const AppbarSidebarAcademyCoursesCourseIdRoute =
  AppbarSidebarAcademyCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AppbarSidebarAcademyCoursesRoute,
  } as any)
const AppbarAdminSidebarSubscriptionsListRoute =
  AppbarAdminSidebarSubscriptionsListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AppbarAdminSidebarSubscriptionsRoute,
  } as any)
const AppbarAdminSidebarSubscriptionsCategoriesRoute =
  AppbarAdminSidebarSubscriptionsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AppbarAdminSidebarSubscriptionsRoute,
  } as any)
const AppbarAdminSidebarSiteAssetsListRoute =
  AppbarAdminSidebarSiteAssetsListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AppbarAdminSidebarSiteAssetsRoute,
  } as any)
const AppbarAdminSidebarSiteAssetsAddRoute =
  AppbarAdminSidebarSiteAssetsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AppbarAdminSidebarSiteAssetsRoute,
  } as any)
const AppbarAdminSidebarCredentialsListRoute =
  AppbarAdminSidebarCredentialsListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AppbarAdminSidebarCredentialsRoute,
  } as any)
const AppbarAdminSidebarCredentialsCategoriesRoute =
  AppbarAdminSidebarCredentialsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AppbarAdminSidebarCredentialsRoute,
  } as any)
const AppbarAdminSidebarAssetsPersonnelRoute =
  AppbarAdminSidebarAssetsPersonnelRouteImport.update({
    id: '/personnel',
    path: '/personnel',
    getParentRoute: () => AppbarAdminSidebarAssetsRoute,
  } as any)
const AppbarAdminSidebarAssetsLocationRoute =
  AppbarAdminSidebarAssetsLocationRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => AppbarAdminSidebarAssetsRoute,
  } as any)
const AppbarAdminSidebarAssetsDevicesRoute =
  AppbarAdminSidebarAssetsDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => AppbarAdminSidebarAssetsRoute,
  } as any)
const AppbarAdminSidebarAccessResourcesRoute =
  AppbarAdminSidebarAccessResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AppbarAdminSidebarAccessRoute,
  } as any)
const AppbarAdminSidebarAccessPersonnelRoute =
  AppbarAdminSidebarAccessPersonnelRouteImport.update({
    id: '/personnel',
    path: '/personnel',
    getParentRoute: () => AppbarAdminSidebarAccessRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppbarIndexRoute
  '/login': typeof authLoginRoute
  '/hub': typeof AppbarSidebarHubRouteWithChildren
  '/issues': typeof AppbarIssuesRoute
  '/fuel-invoicing': typeof AppbarFuelFuelInvoicingRoute
  '/fuel-rec': typeof AppbarFuelFuelRecRoute
  '/kardpoll': typeof AppbarFuelKardpollRoute
  '/cipher': typeof AppbarSidebarCipherRouteWithChildren
  '/inventory': typeof AppbarSidebarInventoryRouteWithChildren
  '/settings': typeof AppbarSidebarSettingsRouteWithChildren
  '/access': typeof AppbarAdminSidebarAccessRouteWithChildren
  '/assets': typeof AppbarAdminSidebarAssetsRouteWithChildren
  '/credentials': typeof AppbarAdminSidebarCredentialsRouteWithChildren
  '/personnel': typeof AppbarAdminSidebarPersonnelRouteWithChildren
  '/site-assets': typeof AppbarAdminSidebarSiteAssetsRouteWithChildren
  '/subscriptions': typeof AppbarAdminSidebarSubscriptionsRouteWithChildren
  '/academy/courses': typeof AppbarSidebarAcademyCoursesRouteWithChildren
  '/cipher/lock': typeof AppbarSidebarCipherLockRoute
  '/cipher/unlock': typeof AppbarSidebarCipherUnlockRoute
  '/hub/cdn': typeof AppbarSidebarHubCdnRoute
  '/hub/payables': typeof AppbarSidebarHubPayablesRoute
  '/hub/receivables': typeof AppbarSidebarHubReceivablesRoute
  '/inventory/coremark-initial-order': typeof AppbarSidebarInventoryCoremarkInitialOrderRoute
  '/settings/logs': typeof AppbarSidebarSettingsLogsRoute
  '/settings/roles': typeof AppbarSidebarSettingsRolesRoute
  '/settings/users': typeof AppbarSidebarSettingsUsersRoute
  '/access/personnel': typeof AppbarAdminSidebarAccessPersonnelRoute
  '/access/resources': typeof AppbarAdminSidebarAccessResourcesRoute
  '/assets/devices': typeof AppbarAdminSidebarAssetsDevicesRoute
  '/assets/location': typeof AppbarAdminSidebarAssetsLocationRoute
  '/assets/personnel': typeof AppbarAdminSidebarAssetsPersonnelRoute
  '/credentials/categories': typeof AppbarAdminSidebarCredentialsCategoriesRoute
  '/credentials/list': typeof AppbarAdminSidebarCredentialsListRoute
  '/site-assets/add': typeof AppbarAdminSidebarSiteAssetsAddRoute
  '/site-assets/list': typeof AppbarAdminSidebarSiteAssetsListRoute
  '/subscriptions/categories': typeof AppbarAdminSidebarSubscriptionsCategoriesRoute
  '/subscriptions/list': typeof AppbarAdminSidebarSubscriptionsListRoute
  '/academy/courses/$courseId': typeof AppbarSidebarAcademyCoursesCourseIdRoute
  '/personnel/': typeof AppbarAdminSidebarPersonnelIndexRoute
  '/site-assets/': typeof AppbarAdminSidebarSiteAssetsIndexRoute
  '/academy/courses/': typeof AppbarSidebarAcademyCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/': typeof AppbarIndexRoute
  '/hub': typeof AppbarSidebarHubRouteWithChildren
  '/issues': typeof AppbarIssuesRoute
  '/fuel-invoicing': typeof AppbarFuelFuelInvoicingRoute
  '/fuel-rec': typeof AppbarFuelFuelRecRoute
  '/kardpoll': typeof AppbarFuelKardpollRoute
  '/cipher': typeof AppbarSidebarCipherRouteWithChildren
  '/inventory': typeof AppbarSidebarInventoryRouteWithChildren
  '/settings': typeof AppbarSidebarSettingsRouteWithChildren
  '/access': typeof AppbarAdminSidebarAccessRouteWithChildren
  '/assets': typeof AppbarAdminSidebarAssetsRouteWithChildren
  '/credentials': typeof AppbarAdminSidebarCredentialsRouteWithChildren
  '/subscriptions': typeof AppbarAdminSidebarSubscriptionsRouteWithChildren
  '/cipher/lock': typeof AppbarSidebarCipherLockRoute
  '/cipher/unlock': typeof AppbarSidebarCipherUnlockRoute
  '/hub/cdn': typeof AppbarSidebarHubCdnRoute
  '/hub/payables': typeof AppbarSidebarHubPayablesRoute
  '/hub/receivables': typeof AppbarSidebarHubReceivablesRoute
  '/inventory/coremark-initial-order': typeof AppbarSidebarInventoryCoremarkInitialOrderRoute
  '/settings/logs': typeof AppbarSidebarSettingsLogsRoute
  '/settings/roles': typeof AppbarSidebarSettingsRolesRoute
  '/settings/users': typeof AppbarSidebarSettingsUsersRoute
  '/access/personnel': typeof AppbarAdminSidebarAccessPersonnelRoute
  '/access/resources': typeof AppbarAdminSidebarAccessResourcesRoute
  '/assets/devices': typeof AppbarAdminSidebarAssetsDevicesRoute
  '/assets/location': typeof AppbarAdminSidebarAssetsLocationRoute
  '/assets/personnel': typeof AppbarAdminSidebarAssetsPersonnelRoute
  '/credentials/categories': typeof AppbarAdminSidebarCredentialsCategoriesRoute
  '/credentials/list': typeof AppbarAdminSidebarCredentialsListRoute
  '/site-assets/add': typeof AppbarAdminSidebarSiteAssetsAddRoute
  '/site-assets/list': typeof AppbarAdminSidebarSiteAssetsListRoute
  '/subscriptions/categories': typeof AppbarAdminSidebarSubscriptionsCategoriesRoute
  '/subscriptions/list': typeof AppbarAdminSidebarSubscriptionsListRoute
  '/academy/courses/$courseId': typeof AppbarSidebarAcademyCoursesCourseIdRoute
  '/personnel': typeof AppbarAdminSidebarPersonnelIndexRoute
  '/site-assets': typeof AppbarAdminSidebarSiteAssetsIndexRoute
  '/academy/courses': typeof AppbarSidebarAcademyCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appbar': typeof AppbarRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_appbar/_admin': typeof AppbarAdminRouteWithChildren
  '/_appbar/_fuel': typeof AppbarFuelRouteWithChildren
  '/_appbar/_sidebar': typeof AppbarSidebarRouteWithChildren
  '/_appbar/hub': typeof AppbarHubRoute
  '/_appbar/issues': typeof AppbarIssuesRoute
  '/_appbar/': typeof AppbarIndexRoute
  '/_appbar/_admin/_sidebar': typeof AppbarAdminSidebarRouteWithChildren
  '/_appbar/_fuel/fuel-invoicing': typeof AppbarFuelFuelInvoicingRoute
  '/_appbar/_fuel/fuel-rec': typeof AppbarFuelFuelRecRoute
  '/_appbar/_fuel/kardpoll': typeof AppbarFuelKardpollRoute
  '/_appbar/_sidebar/cipher': typeof AppbarSidebarCipherRouteWithChildren
  '/_appbar/_sidebar/hub': typeof AppbarSidebarHubRouteWithChildren
  '/_appbar/_sidebar/inventory': typeof AppbarSidebarInventoryRouteWithChildren
  '/_appbar/_sidebar/settings': typeof AppbarSidebarSettingsRouteWithChildren
  '/_appbar/_admin/_sidebar/access': typeof AppbarAdminSidebarAccessRouteWithChildren
  '/_appbar/_admin/_sidebar/assets': typeof AppbarAdminSidebarAssetsRouteWithChildren
  '/_appbar/_admin/_sidebar/credentials': typeof AppbarAdminSidebarCredentialsRouteWithChildren
  '/_appbar/_admin/_sidebar/personnel': typeof AppbarAdminSidebarPersonnelRouteWithChildren
  '/_appbar/_admin/_sidebar/site-assets': typeof AppbarAdminSidebarSiteAssetsRouteWithChildren
  '/_appbar/_admin/_sidebar/subscriptions': typeof AppbarAdminSidebarSubscriptionsRouteWithChildren
  '/_appbar/_sidebar/academy/courses': typeof AppbarSidebarAcademyCoursesRouteWithChildren
  '/_appbar/_sidebar/cipher/lock': typeof AppbarSidebarCipherLockRoute
  '/_appbar/_sidebar/cipher/unlock': typeof AppbarSidebarCipherUnlockRoute
  '/_appbar/_sidebar/hub/cdn': typeof AppbarSidebarHubCdnRoute
  '/_appbar/_sidebar/hub/payables': typeof AppbarSidebarHubPayablesRoute
  '/_appbar/_sidebar/hub/receivables': typeof AppbarSidebarHubReceivablesRoute
  '/_appbar/_sidebar/inventory/coremark-initial-order': typeof AppbarSidebarInventoryCoremarkInitialOrderRoute
  '/_appbar/_sidebar/settings/logs': typeof AppbarSidebarSettingsLogsRoute
  '/_appbar/_sidebar/settings/roles': typeof AppbarSidebarSettingsRolesRoute
  '/_appbar/_sidebar/settings/users': typeof AppbarSidebarSettingsUsersRoute
  '/_appbar/_admin/_sidebar/access/personnel': typeof AppbarAdminSidebarAccessPersonnelRoute
  '/_appbar/_admin/_sidebar/access/resources': typeof AppbarAdminSidebarAccessResourcesRoute
  '/_appbar/_admin/_sidebar/assets/devices': typeof AppbarAdminSidebarAssetsDevicesRoute
  '/_appbar/_admin/_sidebar/assets/location': typeof AppbarAdminSidebarAssetsLocationRoute
  '/_appbar/_admin/_sidebar/assets/personnel': typeof AppbarAdminSidebarAssetsPersonnelRoute
  '/_appbar/_admin/_sidebar/credentials/categories': typeof AppbarAdminSidebarCredentialsCategoriesRoute
  '/_appbar/_admin/_sidebar/credentials/list': typeof AppbarAdminSidebarCredentialsListRoute
  '/_appbar/_admin/_sidebar/site-assets/add': typeof AppbarAdminSidebarSiteAssetsAddRoute
  '/_appbar/_admin/_sidebar/site-assets/list': typeof AppbarAdminSidebarSiteAssetsListRoute
  '/_appbar/_admin/_sidebar/subscriptions/categories': typeof AppbarAdminSidebarSubscriptionsCategoriesRoute
  '/_appbar/_admin/_sidebar/subscriptions/list': typeof AppbarAdminSidebarSubscriptionsListRoute
  '/_appbar/_sidebar/academy/courses/$courseId': typeof AppbarSidebarAcademyCoursesCourseIdRoute
  '/_appbar/_admin/_sidebar/personnel/': typeof AppbarAdminSidebarPersonnelIndexRoute
  '/_appbar/_admin/_sidebar/site-assets/': typeof AppbarAdminSidebarSiteAssetsIndexRoute
  '/_appbar/_sidebar/academy/courses/': typeof AppbarSidebarAcademyCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/hub'
    | '/issues'
    | '/fuel-invoicing'
    | '/fuel-rec'
    | '/kardpoll'
    | '/cipher'
    | '/inventory'
    | '/settings'
    | '/access'
    | '/assets'
    | '/credentials'
    | '/personnel'
    | '/site-assets'
    | '/subscriptions'
    | '/academy/courses'
    | '/cipher/lock'
    | '/cipher/unlock'
    | '/hub/cdn'
    | '/hub/payables'
    | '/hub/receivables'
    | '/inventory/coremark-initial-order'
    | '/settings/logs'
    | '/settings/roles'
    | '/settings/users'
    | '/access/personnel'
    | '/access/resources'
    | '/assets/devices'
    | '/assets/location'
    | '/assets/personnel'
    | '/credentials/categories'
    | '/credentials/list'
    | '/site-assets/add'
    | '/site-assets/list'
    | '/subscriptions/categories'
    | '/subscriptions/list'
    | '/academy/courses/$courseId'
    | '/personnel/'
    | '/site-assets/'
    | '/academy/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/hub'
    | '/issues'
    | '/fuel-invoicing'
    | '/fuel-rec'
    | '/kardpoll'
    | '/cipher'
    | '/inventory'
    | '/settings'
    | '/access'
    | '/assets'
    | '/credentials'
    | '/subscriptions'
    | '/cipher/lock'
    | '/cipher/unlock'
    | '/hub/cdn'
    | '/hub/payables'
    | '/hub/receivables'
    | '/inventory/coremark-initial-order'
    | '/settings/logs'
    | '/settings/roles'
    | '/settings/users'
    | '/access/personnel'
    | '/access/resources'
    | '/assets/devices'
    | '/assets/location'
    | '/assets/personnel'
    | '/credentials/categories'
    | '/credentials/list'
    | '/site-assets/add'
    | '/site-assets/list'
    | '/subscriptions/categories'
    | '/subscriptions/list'
    | '/academy/courses/$courseId'
    | '/personnel'
    | '/site-assets'
    | '/academy/courses'
  id:
    | '__root__'
    | '/_appbar'
    | '/(auth)/login'
    | '/_appbar/_admin'
    | '/_appbar/_fuel'
    | '/_appbar/_sidebar'
    | '/_appbar/hub'
    | '/_appbar/issues'
    | '/_appbar/'
    | '/_appbar/_admin/_sidebar'
    | '/_appbar/_fuel/fuel-invoicing'
    | '/_appbar/_fuel/fuel-rec'
    | '/_appbar/_fuel/kardpoll'
    | '/_appbar/_sidebar/cipher'
    | '/_appbar/_sidebar/hub'
    | '/_appbar/_sidebar/inventory'
    | '/_appbar/_sidebar/settings'
    | '/_appbar/_admin/_sidebar/access'
    | '/_appbar/_admin/_sidebar/assets'
    | '/_appbar/_admin/_sidebar/credentials'
    | '/_appbar/_admin/_sidebar/personnel'
    | '/_appbar/_admin/_sidebar/site-assets'
    | '/_appbar/_admin/_sidebar/subscriptions'
    | '/_appbar/_sidebar/academy/courses'
    | '/_appbar/_sidebar/cipher/lock'
    | '/_appbar/_sidebar/cipher/unlock'
    | '/_appbar/_sidebar/hub/cdn'
    | '/_appbar/_sidebar/hub/payables'
    | '/_appbar/_sidebar/hub/receivables'
    | '/_appbar/_sidebar/inventory/coremark-initial-order'
    | '/_appbar/_sidebar/settings/logs'
    | '/_appbar/_sidebar/settings/roles'
    | '/_appbar/_sidebar/settings/users'
    | '/_appbar/_admin/_sidebar/access/personnel'
    | '/_appbar/_admin/_sidebar/access/resources'
    | '/_appbar/_admin/_sidebar/assets/devices'
    | '/_appbar/_admin/_sidebar/assets/location'
    | '/_appbar/_admin/_sidebar/assets/personnel'
    | '/_appbar/_admin/_sidebar/credentials/categories'
    | '/_appbar/_admin/_sidebar/credentials/list'
    | '/_appbar/_admin/_sidebar/site-assets/add'
    | '/_appbar/_admin/_sidebar/site-assets/list'
    | '/_appbar/_admin/_sidebar/subscriptions/categories'
    | '/_appbar/_admin/_sidebar/subscriptions/list'
    | '/_appbar/_sidebar/academy/courses/$courseId'
    | '/_appbar/_admin/_sidebar/personnel/'
    | '/_appbar/_admin/_sidebar/site-assets/'
    | '/_appbar/_sidebar/academy/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppbarRoute: typeof AppbarRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_appbar': {
      id: '/_appbar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appbar/': {
      id: '/_appbar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppbarIndexRouteImport
      parentRoute: typeof AppbarRoute
    }
    '/_appbar/issues': {
      id: '/_appbar/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof AppbarIssuesRouteImport
      parentRoute: typeof AppbarRoute
    }
    '/_appbar/hub': {
      id: '/_appbar/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AppbarHubRouteImport
      parentRoute: typeof AppbarRoute
    }
    '/_appbar/_sidebar': {
      id: '/_appbar/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppbarSidebarRouteImport
      parentRoute: typeof AppbarRoute
    }
    '/_appbar/_fuel': {
      id: '/_appbar/_fuel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppbarFuelRouteImport
      parentRoute: typeof AppbarRoute
    }
    '/_appbar/_admin': {
      id: '/_appbar/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppbarAdminRouteImport
      parentRoute: typeof AppbarRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appbar/_sidebar/settings': {
      id: '/_appbar/_sidebar/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppbarSidebarSettingsRouteImport
      parentRoute: typeof AppbarSidebarRoute
    }
    '/_appbar/_sidebar/inventory': {
      id: '/_appbar/_sidebar/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppbarSidebarInventoryRouteImport
      parentRoute: typeof AppbarSidebarRoute
    }
    '/_appbar/_sidebar/hub': {
      id: '/_appbar/_sidebar/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AppbarSidebarHubRouteImport
      parentRoute: typeof AppbarSidebarRoute
    }
    '/_appbar/_sidebar/cipher': {
      id: '/_appbar/_sidebar/cipher'
      path: '/cipher'
      fullPath: '/cipher'
      preLoaderRoute: typeof AppbarSidebarCipherRouteImport
      parentRoute: typeof AppbarSidebarRoute
    }
    '/_appbar/_fuel/kardpoll': {
      id: '/_appbar/_fuel/kardpoll'
      path: '/kardpoll'
      fullPath: '/kardpoll'
      preLoaderRoute: typeof AppbarFuelKardpollRouteImport
      parentRoute: typeof AppbarFuelRoute
    }
    '/_appbar/_fuel/fuel-rec': {
      id: '/_appbar/_fuel/fuel-rec'
      path: '/fuel-rec'
      fullPath: '/fuel-rec'
      preLoaderRoute: typeof AppbarFuelFuelRecRouteImport
      parentRoute: typeof AppbarFuelRoute
    }
    '/_appbar/_fuel/fuel-invoicing': {
      id: '/_appbar/_fuel/fuel-invoicing'
      path: '/fuel-invoicing'
      fullPath: '/fuel-invoicing'
      preLoaderRoute: typeof AppbarFuelFuelInvoicingRouteImport
      parentRoute: typeof AppbarFuelRoute
    }
    '/_appbar/_admin/_sidebar': {
      id: '/_appbar/_admin/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppbarAdminSidebarRouteImport
      parentRoute: typeof AppbarAdminRoute
    }
    '/_appbar/_sidebar/settings/users': {
      id: '/_appbar/_sidebar/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppbarSidebarSettingsUsersRouteImport
      parentRoute: typeof AppbarSidebarSettingsRoute
    }
    '/_appbar/_sidebar/settings/roles': {
      id: '/_appbar/_sidebar/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppbarSidebarSettingsRolesRouteImport
      parentRoute: typeof AppbarSidebarSettingsRoute
    }
    '/_appbar/_sidebar/settings/logs': {
      id: '/_appbar/_sidebar/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof AppbarSidebarSettingsLogsRouteImport
      parentRoute: typeof AppbarSidebarSettingsRoute
    }
    '/_appbar/_sidebar/inventory/coremark-initial-order': {
      id: '/_appbar/_sidebar/inventory/coremark-initial-order'
      path: '/coremark-initial-order'
      fullPath: '/inventory/coremark-initial-order'
      preLoaderRoute: typeof AppbarSidebarInventoryCoremarkInitialOrderRouteImport
      parentRoute: typeof AppbarSidebarInventoryRoute
    }
    '/_appbar/_sidebar/hub/receivables': {
      id: '/_appbar/_sidebar/hub/receivables'
      path: '/receivables'
      fullPath: '/hub/receivables'
      preLoaderRoute: typeof AppbarSidebarHubReceivablesRouteImport
      parentRoute: typeof AppbarSidebarHubRoute
    }
    '/_appbar/_sidebar/hub/payables': {
      id: '/_appbar/_sidebar/hub/payables'
      path: '/payables'
      fullPath: '/hub/payables'
      preLoaderRoute: typeof AppbarSidebarHubPayablesRouteImport
      parentRoute: typeof AppbarSidebarHubRoute
    }
    '/_appbar/_sidebar/hub/cdn': {
      id: '/_appbar/_sidebar/hub/cdn'
      path: '/cdn'
      fullPath: '/hub/cdn'
      preLoaderRoute: typeof AppbarSidebarHubCdnRouteImport
      parentRoute: typeof AppbarSidebarHubRoute
    }
    '/_appbar/_sidebar/cipher/unlock': {
      id: '/_appbar/_sidebar/cipher/unlock'
      path: '/unlock'
      fullPath: '/cipher/unlock'
      preLoaderRoute: typeof AppbarSidebarCipherUnlockRouteImport
      parentRoute: typeof AppbarSidebarCipherRoute
    }
    '/_appbar/_sidebar/cipher/lock': {
      id: '/_appbar/_sidebar/cipher/lock'
      path: '/lock'
      fullPath: '/cipher/lock'
      preLoaderRoute: typeof AppbarSidebarCipherLockRouteImport
      parentRoute: typeof AppbarSidebarCipherRoute
    }
    '/_appbar/_sidebar/academy/courses': {
      id: '/_appbar/_sidebar/academy/courses'
      path: '/academy/courses'
      fullPath: '/academy/courses'
      preLoaderRoute: typeof AppbarSidebarAcademyCoursesRouteImport
      parentRoute: typeof AppbarSidebarRoute
    }
    '/_appbar/_admin/_sidebar/subscriptions': {
      id: '/_appbar/_admin/_sidebar/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppbarAdminSidebarSubscriptionsRouteImport
      parentRoute: typeof AppbarAdminSidebarRoute
    }
    '/_appbar/_admin/_sidebar/site-assets': {
      id: '/_appbar/_admin/_sidebar/site-assets'
      path: '/site-assets'
      fullPath: '/site-assets'
      preLoaderRoute: typeof AppbarAdminSidebarSiteAssetsRouteImport
      parentRoute: typeof AppbarAdminSidebarRoute
    }
    '/_appbar/_admin/_sidebar/personnel': {
      id: '/_appbar/_admin/_sidebar/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof AppbarAdminSidebarPersonnelRouteImport
      parentRoute: typeof AppbarAdminSidebarRoute
    }
    '/_appbar/_admin/_sidebar/credentials': {
      id: '/_appbar/_admin/_sidebar/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof AppbarAdminSidebarCredentialsRouteImport
      parentRoute: typeof AppbarAdminSidebarRoute
    }
    '/_appbar/_admin/_sidebar/assets': {
      id: '/_appbar/_admin/_sidebar/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppbarAdminSidebarAssetsRouteImport
      parentRoute: typeof AppbarAdminSidebarRoute
    }
    '/_appbar/_admin/_sidebar/access': {
      id: '/_appbar/_admin/_sidebar/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppbarAdminSidebarAccessRouteImport
      parentRoute: typeof AppbarAdminSidebarRoute
    }
    '/_appbar/_sidebar/academy/courses/': {
      id: '/_appbar/_sidebar/academy/courses/'
      path: '/'
      fullPath: '/academy/courses/'
      preLoaderRoute: typeof AppbarSidebarAcademyCoursesIndexRouteImport
      parentRoute: typeof AppbarSidebarAcademyCoursesRoute
    }
    '/_appbar/_admin/_sidebar/site-assets/': {
      id: '/_appbar/_admin/_sidebar/site-assets/'
      path: '/'
      fullPath: '/site-assets/'
      preLoaderRoute: typeof AppbarAdminSidebarSiteAssetsIndexRouteImport
      parentRoute: typeof AppbarAdminSidebarSiteAssetsRoute
    }
    '/_appbar/_admin/_sidebar/personnel/': {
      id: '/_appbar/_admin/_sidebar/personnel/'
      path: '/'
      fullPath: '/personnel/'
      preLoaderRoute: typeof AppbarAdminSidebarPersonnelIndexRouteImport
      parentRoute: typeof AppbarAdminSidebarPersonnelRoute
    }
    '/_appbar/_sidebar/academy/courses/$courseId': {
      id: '/_appbar/_sidebar/academy/courses/$courseId'
      path: '/$courseId'
      fullPath: '/academy/courses/$courseId'
      preLoaderRoute: typeof AppbarSidebarAcademyCoursesCourseIdRouteImport
      parentRoute: typeof AppbarSidebarAcademyCoursesRoute
    }
    '/_appbar/_admin/_sidebar/subscriptions/list': {
      id: '/_appbar/_admin/_sidebar/subscriptions/list'
      path: '/list'
      fullPath: '/subscriptions/list'
      preLoaderRoute: typeof AppbarAdminSidebarSubscriptionsListRouteImport
      parentRoute: typeof AppbarAdminSidebarSubscriptionsRoute
    }
    '/_appbar/_admin/_sidebar/subscriptions/categories': {
      id: '/_appbar/_admin/_sidebar/subscriptions/categories'
      path: '/categories'
      fullPath: '/subscriptions/categories'
      preLoaderRoute: typeof AppbarAdminSidebarSubscriptionsCategoriesRouteImport
      parentRoute: typeof AppbarAdminSidebarSubscriptionsRoute
    }
    '/_appbar/_admin/_sidebar/site-assets/list': {
      id: '/_appbar/_admin/_sidebar/site-assets/list'
      path: '/list'
      fullPath: '/site-assets/list'
      preLoaderRoute: typeof AppbarAdminSidebarSiteAssetsListRouteImport
      parentRoute: typeof AppbarAdminSidebarSiteAssetsRoute
    }
    '/_appbar/_admin/_sidebar/site-assets/add': {
      id: '/_appbar/_admin/_sidebar/site-assets/add'
      path: '/add'
      fullPath: '/site-assets/add'
      preLoaderRoute: typeof AppbarAdminSidebarSiteAssetsAddRouteImport
      parentRoute: typeof AppbarAdminSidebarSiteAssetsRoute
    }
    '/_appbar/_admin/_sidebar/credentials/list': {
      id: '/_appbar/_admin/_sidebar/credentials/list'
      path: '/list'
      fullPath: '/credentials/list'
      preLoaderRoute: typeof AppbarAdminSidebarCredentialsListRouteImport
      parentRoute: typeof AppbarAdminSidebarCredentialsRoute
    }
    '/_appbar/_admin/_sidebar/credentials/categories': {
      id: '/_appbar/_admin/_sidebar/credentials/categories'
      path: '/categories'
      fullPath: '/credentials/categories'
      preLoaderRoute: typeof AppbarAdminSidebarCredentialsCategoriesRouteImport
      parentRoute: typeof AppbarAdminSidebarCredentialsRoute
    }
    '/_appbar/_admin/_sidebar/assets/personnel': {
      id: '/_appbar/_admin/_sidebar/assets/personnel'
      path: '/personnel'
      fullPath: '/assets/personnel'
      preLoaderRoute: typeof AppbarAdminSidebarAssetsPersonnelRouteImport
      parentRoute: typeof AppbarAdminSidebarAssetsRoute
    }
    '/_appbar/_admin/_sidebar/assets/location': {
      id: '/_appbar/_admin/_sidebar/assets/location'
      path: '/location'
      fullPath: '/assets/location'
      preLoaderRoute: typeof AppbarAdminSidebarAssetsLocationRouteImport
      parentRoute: typeof AppbarAdminSidebarAssetsRoute
    }
    '/_appbar/_admin/_sidebar/assets/devices': {
      id: '/_appbar/_admin/_sidebar/assets/devices'
      path: '/devices'
      fullPath: '/assets/devices'
      preLoaderRoute: typeof AppbarAdminSidebarAssetsDevicesRouteImport
      parentRoute: typeof AppbarAdminSidebarAssetsRoute
    }
    '/_appbar/_admin/_sidebar/access/resources': {
      id: '/_appbar/_admin/_sidebar/access/resources'
      path: '/resources'
      fullPath: '/access/resources'
      preLoaderRoute: typeof AppbarAdminSidebarAccessResourcesRouteImport
      parentRoute: typeof AppbarAdminSidebarAccessRoute
    }
    '/_appbar/_admin/_sidebar/access/personnel': {
      id: '/_appbar/_admin/_sidebar/access/personnel'
      path: '/personnel'
      fullPath: '/access/personnel'
      preLoaderRoute: typeof AppbarAdminSidebarAccessPersonnelRouteImport
      parentRoute: typeof AppbarAdminSidebarAccessRoute
    }
  }
}

interface AppbarAdminSidebarAccessRouteChildren {
  AppbarAdminSidebarAccessPersonnelRoute: typeof AppbarAdminSidebarAccessPersonnelRoute
  AppbarAdminSidebarAccessResourcesRoute: typeof AppbarAdminSidebarAccessResourcesRoute
}

const AppbarAdminSidebarAccessRouteChildren: AppbarAdminSidebarAccessRouteChildren =
  {
    AppbarAdminSidebarAccessPersonnelRoute:
      AppbarAdminSidebarAccessPersonnelRoute,
    AppbarAdminSidebarAccessResourcesRoute:
      AppbarAdminSidebarAccessResourcesRoute,
  }

const AppbarAdminSidebarAccessRouteWithChildren =
  AppbarAdminSidebarAccessRoute._addFileChildren(
    AppbarAdminSidebarAccessRouteChildren,
  )

interface AppbarAdminSidebarAssetsRouteChildren {
  AppbarAdminSidebarAssetsDevicesRoute: typeof AppbarAdminSidebarAssetsDevicesRoute
  AppbarAdminSidebarAssetsLocationRoute: typeof AppbarAdminSidebarAssetsLocationRoute
  AppbarAdminSidebarAssetsPersonnelRoute: typeof AppbarAdminSidebarAssetsPersonnelRoute
}

const AppbarAdminSidebarAssetsRouteChildren: AppbarAdminSidebarAssetsRouteChildren =
  {
    AppbarAdminSidebarAssetsDevicesRoute: AppbarAdminSidebarAssetsDevicesRoute,
    AppbarAdminSidebarAssetsLocationRoute:
      AppbarAdminSidebarAssetsLocationRoute,
    AppbarAdminSidebarAssetsPersonnelRoute:
      AppbarAdminSidebarAssetsPersonnelRoute,
  }

const AppbarAdminSidebarAssetsRouteWithChildren =
  AppbarAdminSidebarAssetsRoute._addFileChildren(
    AppbarAdminSidebarAssetsRouteChildren,
  )

interface AppbarAdminSidebarCredentialsRouteChildren {
  AppbarAdminSidebarCredentialsCategoriesRoute: typeof AppbarAdminSidebarCredentialsCategoriesRoute
  AppbarAdminSidebarCredentialsListRoute: typeof AppbarAdminSidebarCredentialsListRoute
}

const AppbarAdminSidebarCredentialsRouteChildren: AppbarAdminSidebarCredentialsRouteChildren =
  {
    AppbarAdminSidebarCredentialsCategoriesRoute:
      AppbarAdminSidebarCredentialsCategoriesRoute,
    AppbarAdminSidebarCredentialsListRoute:
      AppbarAdminSidebarCredentialsListRoute,
  }

const AppbarAdminSidebarCredentialsRouteWithChildren =
  AppbarAdminSidebarCredentialsRoute._addFileChildren(
    AppbarAdminSidebarCredentialsRouteChildren,
  )

interface AppbarAdminSidebarPersonnelRouteChildren {
  AppbarAdminSidebarPersonnelIndexRoute: typeof AppbarAdminSidebarPersonnelIndexRoute
}

const AppbarAdminSidebarPersonnelRouteChildren: AppbarAdminSidebarPersonnelRouteChildren =
  {
    AppbarAdminSidebarPersonnelIndexRoute:
      AppbarAdminSidebarPersonnelIndexRoute,
  }

const AppbarAdminSidebarPersonnelRouteWithChildren =
  AppbarAdminSidebarPersonnelRoute._addFileChildren(
    AppbarAdminSidebarPersonnelRouteChildren,
  )

interface AppbarAdminSidebarSiteAssetsRouteChildren {
  AppbarAdminSidebarSiteAssetsAddRoute: typeof AppbarAdminSidebarSiteAssetsAddRoute
  AppbarAdminSidebarSiteAssetsListRoute: typeof AppbarAdminSidebarSiteAssetsListRoute
  AppbarAdminSidebarSiteAssetsIndexRoute: typeof AppbarAdminSidebarSiteAssetsIndexRoute
}

const AppbarAdminSidebarSiteAssetsRouteChildren: AppbarAdminSidebarSiteAssetsRouteChildren =
  {
    AppbarAdminSidebarSiteAssetsAddRoute: AppbarAdminSidebarSiteAssetsAddRoute,
    AppbarAdminSidebarSiteAssetsListRoute:
      AppbarAdminSidebarSiteAssetsListRoute,
    AppbarAdminSidebarSiteAssetsIndexRoute:
      AppbarAdminSidebarSiteAssetsIndexRoute,
  }

const AppbarAdminSidebarSiteAssetsRouteWithChildren =
  AppbarAdminSidebarSiteAssetsRoute._addFileChildren(
    AppbarAdminSidebarSiteAssetsRouteChildren,
  )

interface AppbarAdminSidebarSubscriptionsRouteChildren {
  AppbarAdminSidebarSubscriptionsCategoriesRoute: typeof AppbarAdminSidebarSubscriptionsCategoriesRoute
  AppbarAdminSidebarSubscriptionsListRoute: typeof AppbarAdminSidebarSubscriptionsListRoute
}

const AppbarAdminSidebarSubscriptionsRouteChildren: AppbarAdminSidebarSubscriptionsRouteChildren =
  {
    AppbarAdminSidebarSubscriptionsCategoriesRoute:
      AppbarAdminSidebarSubscriptionsCategoriesRoute,
    AppbarAdminSidebarSubscriptionsListRoute:
      AppbarAdminSidebarSubscriptionsListRoute,
  }

const AppbarAdminSidebarSubscriptionsRouteWithChildren =
  AppbarAdminSidebarSubscriptionsRoute._addFileChildren(
    AppbarAdminSidebarSubscriptionsRouteChildren,
  )

interface AppbarAdminSidebarRouteChildren {
  AppbarAdminSidebarAccessRoute: typeof AppbarAdminSidebarAccessRouteWithChildren
  AppbarAdminSidebarAssetsRoute: typeof AppbarAdminSidebarAssetsRouteWithChildren
  AppbarAdminSidebarCredentialsRoute: typeof AppbarAdminSidebarCredentialsRouteWithChildren
  AppbarAdminSidebarPersonnelRoute: typeof AppbarAdminSidebarPersonnelRouteWithChildren
  AppbarAdminSidebarSiteAssetsRoute: typeof AppbarAdminSidebarSiteAssetsRouteWithChildren
  AppbarAdminSidebarSubscriptionsRoute: typeof AppbarAdminSidebarSubscriptionsRouteWithChildren
}

const AppbarAdminSidebarRouteChildren: AppbarAdminSidebarRouteChildren = {
  AppbarAdminSidebarAccessRoute: AppbarAdminSidebarAccessRouteWithChildren,
  AppbarAdminSidebarAssetsRoute: AppbarAdminSidebarAssetsRouteWithChildren,
  AppbarAdminSidebarCredentialsRoute:
    AppbarAdminSidebarCredentialsRouteWithChildren,
  AppbarAdminSidebarPersonnelRoute:
    AppbarAdminSidebarPersonnelRouteWithChildren,
  AppbarAdminSidebarSiteAssetsRoute:
    AppbarAdminSidebarSiteAssetsRouteWithChildren,
  AppbarAdminSidebarSubscriptionsRoute:
    AppbarAdminSidebarSubscriptionsRouteWithChildren,
}

const AppbarAdminSidebarRouteWithChildren =
  AppbarAdminSidebarRoute._addFileChildren(AppbarAdminSidebarRouteChildren)

interface AppbarAdminRouteChildren {
  AppbarAdminSidebarRoute: typeof AppbarAdminSidebarRouteWithChildren
}

const AppbarAdminRouteChildren: AppbarAdminRouteChildren = {
  AppbarAdminSidebarRoute: AppbarAdminSidebarRouteWithChildren,
}

const AppbarAdminRouteWithChildren = AppbarAdminRoute._addFileChildren(
  AppbarAdminRouteChildren,
)

interface AppbarFuelRouteChildren {
  AppbarFuelFuelInvoicingRoute: typeof AppbarFuelFuelInvoicingRoute
  AppbarFuelFuelRecRoute: typeof AppbarFuelFuelRecRoute
  AppbarFuelKardpollRoute: typeof AppbarFuelKardpollRoute
}

const AppbarFuelRouteChildren: AppbarFuelRouteChildren = {
  AppbarFuelFuelInvoicingRoute: AppbarFuelFuelInvoicingRoute,
  AppbarFuelFuelRecRoute: AppbarFuelFuelRecRoute,
  AppbarFuelKardpollRoute: AppbarFuelKardpollRoute,
}

const AppbarFuelRouteWithChildren = AppbarFuelRoute._addFileChildren(
  AppbarFuelRouteChildren,
)

interface AppbarSidebarCipherRouteChildren {
  AppbarSidebarCipherLockRoute: typeof AppbarSidebarCipherLockRoute
  AppbarSidebarCipherUnlockRoute: typeof AppbarSidebarCipherUnlockRoute
}

const AppbarSidebarCipherRouteChildren: AppbarSidebarCipherRouteChildren = {
  AppbarSidebarCipherLockRoute: AppbarSidebarCipherLockRoute,
  AppbarSidebarCipherUnlockRoute: AppbarSidebarCipherUnlockRoute,
}

const AppbarSidebarCipherRouteWithChildren =
  AppbarSidebarCipherRoute._addFileChildren(AppbarSidebarCipherRouteChildren)

interface AppbarSidebarHubRouteChildren {
  AppbarSidebarHubCdnRoute: typeof AppbarSidebarHubCdnRoute
  AppbarSidebarHubPayablesRoute: typeof AppbarSidebarHubPayablesRoute
  AppbarSidebarHubReceivablesRoute: typeof AppbarSidebarHubReceivablesRoute
}

const AppbarSidebarHubRouteChildren: AppbarSidebarHubRouteChildren = {
  AppbarSidebarHubCdnRoute: AppbarSidebarHubCdnRoute,
  AppbarSidebarHubPayablesRoute: AppbarSidebarHubPayablesRoute,
  AppbarSidebarHubReceivablesRoute: AppbarSidebarHubReceivablesRoute,
}

const AppbarSidebarHubRouteWithChildren =
  AppbarSidebarHubRoute._addFileChildren(AppbarSidebarHubRouteChildren)

interface AppbarSidebarInventoryRouteChildren {
  AppbarSidebarInventoryCoremarkInitialOrderRoute: typeof AppbarSidebarInventoryCoremarkInitialOrderRoute
}

const AppbarSidebarInventoryRouteChildren: AppbarSidebarInventoryRouteChildren =
  {
    AppbarSidebarInventoryCoremarkInitialOrderRoute:
      AppbarSidebarInventoryCoremarkInitialOrderRoute,
  }

const AppbarSidebarInventoryRouteWithChildren =
  AppbarSidebarInventoryRoute._addFileChildren(
    AppbarSidebarInventoryRouteChildren,
  )

interface AppbarSidebarSettingsRouteChildren {
  AppbarSidebarSettingsLogsRoute: typeof AppbarSidebarSettingsLogsRoute
  AppbarSidebarSettingsRolesRoute: typeof AppbarSidebarSettingsRolesRoute
  AppbarSidebarSettingsUsersRoute: typeof AppbarSidebarSettingsUsersRoute
}

const AppbarSidebarSettingsRouteChildren: AppbarSidebarSettingsRouteChildren = {
  AppbarSidebarSettingsLogsRoute: AppbarSidebarSettingsLogsRoute,
  AppbarSidebarSettingsRolesRoute: AppbarSidebarSettingsRolesRoute,
  AppbarSidebarSettingsUsersRoute: AppbarSidebarSettingsUsersRoute,
}

const AppbarSidebarSettingsRouteWithChildren =
  AppbarSidebarSettingsRoute._addFileChildren(
    AppbarSidebarSettingsRouteChildren,
  )

interface AppbarSidebarAcademyCoursesRouteChildren {
  AppbarSidebarAcademyCoursesCourseIdRoute: typeof AppbarSidebarAcademyCoursesCourseIdRoute
  AppbarSidebarAcademyCoursesIndexRoute: typeof AppbarSidebarAcademyCoursesIndexRoute
}

const AppbarSidebarAcademyCoursesRouteChildren: AppbarSidebarAcademyCoursesRouteChildren =
  {
    AppbarSidebarAcademyCoursesCourseIdRoute:
      AppbarSidebarAcademyCoursesCourseIdRoute,
    AppbarSidebarAcademyCoursesIndexRoute:
      AppbarSidebarAcademyCoursesIndexRoute,
  }

const AppbarSidebarAcademyCoursesRouteWithChildren =
  AppbarSidebarAcademyCoursesRoute._addFileChildren(
    AppbarSidebarAcademyCoursesRouteChildren,
  )

interface AppbarSidebarRouteChildren {
  AppbarSidebarCipherRoute: typeof AppbarSidebarCipherRouteWithChildren
  AppbarSidebarHubRoute: typeof AppbarSidebarHubRouteWithChildren
  AppbarSidebarInventoryRoute: typeof AppbarSidebarInventoryRouteWithChildren
  AppbarSidebarSettingsRoute: typeof AppbarSidebarSettingsRouteWithChildren
  AppbarSidebarAcademyCoursesRoute: typeof AppbarSidebarAcademyCoursesRouteWithChildren
}

const AppbarSidebarRouteChildren: AppbarSidebarRouteChildren = {
  AppbarSidebarCipherRoute: AppbarSidebarCipherRouteWithChildren,
  AppbarSidebarHubRoute: AppbarSidebarHubRouteWithChildren,
  AppbarSidebarInventoryRoute: AppbarSidebarInventoryRouteWithChildren,
  AppbarSidebarSettingsRoute: AppbarSidebarSettingsRouteWithChildren,
  AppbarSidebarAcademyCoursesRoute:
    AppbarSidebarAcademyCoursesRouteWithChildren,
}

const AppbarSidebarRouteWithChildren = AppbarSidebarRoute._addFileChildren(
  AppbarSidebarRouteChildren,
)

interface AppbarRouteChildren {
  AppbarAdminRoute: typeof AppbarAdminRouteWithChildren
  AppbarFuelRoute: typeof AppbarFuelRouteWithChildren
  AppbarSidebarRoute: typeof AppbarSidebarRouteWithChildren
  AppbarHubRoute: typeof AppbarHubRoute
  AppbarIssuesRoute: typeof AppbarIssuesRoute
  AppbarIndexRoute: typeof AppbarIndexRoute
}

const AppbarRouteChildren: AppbarRouteChildren = {
  AppbarAdminRoute: AppbarAdminRouteWithChildren,
  AppbarFuelRoute: AppbarFuelRouteWithChildren,
  AppbarSidebarRoute: AppbarSidebarRouteWithChildren,
  AppbarHubRoute: AppbarHubRoute,
  AppbarIssuesRoute: AppbarIssuesRoute,
  AppbarIndexRoute: AppbarIndexRoute,
}

const AppbarRouteWithChildren =
  AppbarRoute._addFileChildren(AppbarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppbarRoute: AppbarRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
