/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppbarRouteImport } from './routes/_appbar'
import { Route as AppbarIndexRouteImport } from './routes/_appbar/index'
import { Route as AppbarSubscriptionsRouteImport } from './routes/_appbar/subscriptions'
import { Route as AppbarPersonnelRouteImport } from './routes/_appbar/personnel'
import { Route as AppbarFuelInvoicingRouteImport } from './routes/_appbar/fuel-invoicing'
import { Route as AppbarCredentialsRouteImport } from './routes/_appbar/credentials'
import { Route as AppbarSidebarRouteImport } from './routes/_appbar/_sidebar'
import { Route as AppbarSidebarAssetsRouteImport } from './routes/_appbar/_sidebar/assets'
import { Route as AppbarSidebarAccessRouteImport } from './routes/_appbar/_sidebar/access'
import { Route as AppbarSidebarAssetsPersonnelRouteImport } from './routes/_appbar/_sidebar/assets/personnel'
import { Route as AppbarSidebarAssetsLocationRouteImport } from './routes/_appbar/_sidebar/assets/location'
import { Route as AppbarSidebarAssetsDevicesRouteImport } from './routes/_appbar/_sidebar/assets/devices'
import { Route as AppbarSidebarAccessResourcesRouteImport } from './routes/_appbar/_sidebar/access/resources'
import { Route as AppbarSidebarAccessPersonnelRouteImport } from './routes/_appbar/_sidebar/access/personnel'

const AppbarRoute = AppbarRouteImport.update({
  id: '/_appbar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppbarIndexRoute = AppbarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppbarRoute,
} as any)
const AppbarSubscriptionsRoute = AppbarSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppbarRoute,
} as any)
const AppbarPersonnelRoute = AppbarPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => AppbarRoute,
} as any)
const AppbarFuelInvoicingRoute = AppbarFuelInvoicingRouteImport.update({
  id: '/fuel-invoicing',
  path: '/fuel-invoicing',
  getParentRoute: () => AppbarRoute,
} as any)
const AppbarCredentialsRoute = AppbarCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AppbarRoute,
} as any)
const AppbarSidebarRoute = AppbarSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => AppbarRoute,
} as any)
const AppbarSidebarAssetsRoute = AppbarSidebarAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppbarSidebarRoute,
} as any)
const AppbarSidebarAccessRoute = AppbarSidebarAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppbarSidebarRoute,
} as any)
const AppbarSidebarAssetsPersonnelRoute =
  AppbarSidebarAssetsPersonnelRouteImport.update({
    id: '/personnel',
    path: '/personnel',
    getParentRoute: () => AppbarSidebarAssetsRoute,
  } as any)
const AppbarSidebarAssetsLocationRoute =
  AppbarSidebarAssetsLocationRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => AppbarSidebarAssetsRoute,
  } as any)
const AppbarSidebarAssetsDevicesRoute =
  AppbarSidebarAssetsDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => AppbarSidebarAssetsRoute,
  } as any)
const AppbarSidebarAccessResourcesRoute =
  AppbarSidebarAccessResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AppbarSidebarAccessRoute,
  } as any)
const AppbarSidebarAccessPersonnelRoute =
  AppbarSidebarAccessPersonnelRouteImport.update({
    id: '/personnel',
    path: '/personnel',
    getParentRoute: () => AppbarSidebarAccessRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppbarIndexRoute
  '/credentials': typeof AppbarCredentialsRoute
  '/fuel-invoicing': typeof AppbarFuelInvoicingRoute
  '/personnel': typeof AppbarPersonnelRoute
  '/subscriptions': typeof AppbarSubscriptionsRoute
  '/access': typeof AppbarSidebarAccessRouteWithChildren
  '/assets': typeof AppbarSidebarAssetsRouteWithChildren
  '/access/personnel': typeof AppbarSidebarAccessPersonnelRoute
  '/access/resources': typeof AppbarSidebarAccessResourcesRoute
  '/assets/devices': typeof AppbarSidebarAssetsDevicesRoute
  '/assets/location': typeof AppbarSidebarAssetsLocationRoute
  '/assets/personnel': typeof AppbarSidebarAssetsPersonnelRoute
}
export interface FileRoutesByTo {
  '/': typeof AppbarIndexRoute
  '/credentials': typeof AppbarCredentialsRoute
  '/fuel-invoicing': typeof AppbarFuelInvoicingRoute
  '/personnel': typeof AppbarPersonnelRoute
  '/subscriptions': typeof AppbarSubscriptionsRoute
  '/access': typeof AppbarSidebarAccessRouteWithChildren
  '/assets': typeof AppbarSidebarAssetsRouteWithChildren
  '/access/personnel': typeof AppbarSidebarAccessPersonnelRoute
  '/access/resources': typeof AppbarSidebarAccessResourcesRoute
  '/assets/devices': typeof AppbarSidebarAssetsDevicesRoute
  '/assets/location': typeof AppbarSidebarAssetsLocationRoute
  '/assets/personnel': typeof AppbarSidebarAssetsPersonnelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appbar': typeof AppbarRouteWithChildren
  '/_appbar/_sidebar': typeof AppbarSidebarRouteWithChildren
  '/_appbar/credentials': typeof AppbarCredentialsRoute
  '/_appbar/fuel-invoicing': typeof AppbarFuelInvoicingRoute
  '/_appbar/personnel': typeof AppbarPersonnelRoute
  '/_appbar/subscriptions': typeof AppbarSubscriptionsRoute
  '/_appbar/': typeof AppbarIndexRoute
  '/_appbar/_sidebar/access': typeof AppbarSidebarAccessRouteWithChildren
  '/_appbar/_sidebar/assets': typeof AppbarSidebarAssetsRouteWithChildren
  '/_appbar/_sidebar/access/personnel': typeof AppbarSidebarAccessPersonnelRoute
  '/_appbar/_sidebar/access/resources': typeof AppbarSidebarAccessResourcesRoute
  '/_appbar/_sidebar/assets/devices': typeof AppbarSidebarAssetsDevicesRoute
  '/_appbar/_sidebar/assets/location': typeof AppbarSidebarAssetsLocationRoute
  '/_appbar/_sidebar/assets/personnel': typeof AppbarSidebarAssetsPersonnelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credentials'
    | '/fuel-invoicing'
    | '/personnel'
    | '/subscriptions'
    | '/access'
    | '/assets'
    | '/access/personnel'
    | '/access/resources'
    | '/assets/devices'
    | '/assets/location'
    | '/assets/personnel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credentials'
    | '/fuel-invoicing'
    | '/personnel'
    | '/subscriptions'
    | '/access'
    | '/assets'
    | '/access/personnel'
    | '/access/resources'
    | '/assets/devices'
    | '/assets/location'
    | '/assets/personnel'
  id:
    | '__root__'
    | '/_appbar'
    | '/_appbar/_sidebar'
    | '/_appbar/credentials'
    | '/_appbar/fuel-invoicing'
    | '/_appbar/personnel'
    | '/_appbar/subscriptions'
    | '/_appbar/'
    | '/_appbar/_sidebar/access'
    | '/_appbar/_sidebar/assets'
    | '/_appbar/_sidebar/access/personnel'
    | '/_appbar/_sidebar/access/resources'
    | '/_appbar/_sidebar/assets/devices'
    | '/_appbar/_sidebar/assets/location'
    | '/_appbar/_sidebar/assets/personnel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppbarRoute: typeof AppbarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_appbar': {
      id: '/_appbar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appbar/': {
      id: '/_appbar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppbarIndexRouteImport
      parentRoute: typeof AppbarRoute
    }
    '/_appbar/subscriptions': {
      id: '/_appbar/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppbarSubscriptionsRouteImport
      parentRoute: typeof AppbarRoute
    }
    '/_appbar/personnel': {
      id: '/_appbar/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof AppbarPersonnelRouteImport
      parentRoute: typeof AppbarRoute
    }
    '/_appbar/fuel-invoicing': {
      id: '/_appbar/fuel-invoicing'
      path: '/fuel-invoicing'
      fullPath: '/fuel-invoicing'
      preLoaderRoute: typeof AppbarFuelInvoicingRouteImport
      parentRoute: typeof AppbarRoute
    }
    '/_appbar/credentials': {
      id: '/_appbar/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof AppbarCredentialsRouteImport
      parentRoute: typeof AppbarRoute
    }
    '/_appbar/_sidebar': {
      id: '/_appbar/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppbarSidebarRouteImport
      parentRoute: typeof AppbarRoute
    }
    '/_appbar/_sidebar/assets': {
      id: '/_appbar/_sidebar/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppbarSidebarAssetsRouteImport
      parentRoute: typeof AppbarSidebarRoute
    }
    '/_appbar/_sidebar/access': {
      id: '/_appbar/_sidebar/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppbarSidebarAccessRouteImport
      parentRoute: typeof AppbarSidebarRoute
    }
    '/_appbar/_sidebar/assets/personnel': {
      id: '/_appbar/_sidebar/assets/personnel'
      path: '/personnel'
      fullPath: '/assets/personnel'
      preLoaderRoute: typeof AppbarSidebarAssetsPersonnelRouteImport
      parentRoute: typeof AppbarSidebarAssetsRoute
    }
    '/_appbar/_sidebar/assets/location': {
      id: '/_appbar/_sidebar/assets/location'
      path: '/location'
      fullPath: '/assets/location'
      preLoaderRoute: typeof AppbarSidebarAssetsLocationRouteImport
      parentRoute: typeof AppbarSidebarAssetsRoute
    }
    '/_appbar/_sidebar/assets/devices': {
      id: '/_appbar/_sidebar/assets/devices'
      path: '/devices'
      fullPath: '/assets/devices'
      preLoaderRoute: typeof AppbarSidebarAssetsDevicesRouteImport
      parentRoute: typeof AppbarSidebarAssetsRoute
    }
    '/_appbar/_sidebar/access/resources': {
      id: '/_appbar/_sidebar/access/resources'
      path: '/resources'
      fullPath: '/access/resources'
      preLoaderRoute: typeof AppbarSidebarAccessResourcesRouteImport
      parentRoute: typeof AppbarSidebarAccessRoute
    }
    '/_appbar/_sidebar/access/personnel': {
      id: '/_appbar/_sidebar/access/personnel'
      path: '/personnel'
      fullPath: '/access/personnel'
      preLoaderRoute: typeof AppbarSidebarAccessPersonnelRouteImport
      parentRoute: typeof AppbarSidebarAccessRoute
    }
  }
}

interface AppbarSidebarAccessRouteChildren {
  AppbarSidebarAccessPersonnelRoute: typeof AppbarSidebarAccessPersonnelRoute
  AppbarSidebarAccessResourcesRoute: typeof AppbarSidebarAccessResourcesRoute
}

const AppbarSidebarAccessRouteChildren: AppbarSidebarAccessRouteChildren = {
  AppbarSidebarAccessPersonnelRoute: AppbarSidebarAccessPersonnelRoute,
  AppbarSidebarAccessResourcesRoute: AppbarSidebarAccessResourcesRoute,
}

const AppbarSidebarAccessRouteWithChildren =
  AppbarSidebarAccessRoute._addFileChildren(AppbarSidebarAccessRouteChildren)

interface AppbarSidebarAssetsRouteChildren {
  AppbarSidebarAssetsDevicesRoute: typeof AppbarSidebarAssetsDevicesRoute
  AppbarSidebarAssetsLocationRoute: typeof AppbarSidebarAssetsLocationRoute
  AppbarSidebarAssetsPersonnelRoute: typeof AppbarSidebarAssetsPersonnelRoute
}

const AppbarSidebarAssetsRouteChildren: AppbarSidebarAssetsRouteChildren = {
  AppbarSidebarAssetsDevicesRoute: AppbarSidebarAssetsDevicesRoute,
  AppbarSidebarAssetsLocationRoute: AppbarSidebarAssetsLocationRoute,
  AppbarSidebarAssetsPersonnelRoute: AppbarSidebarAssetsPersonnelRoute,
}

const AppbarSidebarAssetsRouteWithChildren =
  AppbarSidebarAssetsRoute._addFileChildren(AppbarSidebarAssetsRouteChildren)

interface AppbarSidebarRouteChildren {
  AppbarSidebarAccessRoute: typeof AppbarSidebarAccessRouteWithChildren
  AppbarSidebarAssetsRoute: typeof AppbarSidebarAssetsRouteWithChildren
}

const AppbarSidebarRouteChildren: AppbarSidebarRouteChildren = {
  AppbarSidebarAccessRoute: AppbarSidebarAccessRouteWithChildren,
  AppbarSidebarAssetsRoute: AppbarSidebarAssetsRouteWithChildren,
}

const AppbarSidebarRouteWithChildren = AppbarSidebarRoute._addFileChildren(
  AppbarSidebarRouteChildren,
)

interface AppbarRouteChildren {
  AppbarSidebarRoute: typeof AppbarSidebarRouteWithChildren
  AppbarCredentialsRoute: typeof AppbarCredentialsRoute
  AppbarFuelInvoicingRoute: typeof AppbarFuelInvoicingRoute
  AppbarPersonnelRoute: typeof AppbarPersonnelRoute
  AppbarSubscriptionsRoute: typeof AppbarSubscriptionsRoute
  AppbarIndexRoute: typeof AppbarIndexRoute
}

const AppbarRouteChildren: AppbarRouteChildren = {
  AppbarSidebarRoute: AppbarSidebarRouteWithChildren,
  AppbarCredentialsRoute: AppbarCredentialsRoute,
  AppbarFuelInvoicingRoute: AppbarFuelInvoicingRoute,
  AppbarPersonnelRoute: AppbarPersonnelRoute,
  AppbarSubscriptionsRoute: AppbarSubscriptionsRoute,
  AppbarIndexRoute: AppbarIndexRoute,
}

const AppbarRouteWithChildren =
  AppbarRoute._addFileChildren(AppbarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppbarRoute: AppbarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
